# .github/workflows/generate-chart-data.yml
name: Generate and Upload Multi-Coin Chart Data to R2

on:
  workflow_dispatch: # Memungkinkan Anda menjalankan workflow secara manual dari GitHub UI
  schedule:
    - cron: '*/24 * * * *' # Jalankan setiap 24 menit (UTC)

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Menggunakan Node.js versi 20
          cache: 'npm' # Mengaktifkan caching untuk npm dependencies
          # Karena kita tidak punya package-lock.json saat ini, kita bisa HAPUS cache-dependency-path UNTUK EKSEKUSI PERTAMA
          # Atau, jika Anda yakin package-lock.json akan tergenerate oleh npm install, biarkan.
          # Untuk pertama kali dan memastikan tidak error, mari kita coba HILANGKAN path-nya dulu.
          # cache-dependency-path: package-lock.json # <-- HILANGKAN BARIS INI UNTUK EKSEKUSI PERTAMA

      - name: Install dependencies (will generate package-lock.json)
        run: npm install # Gunakan 'npm install' agar package-lock.json tergenerate

      - name: Generate Chart Data JSON
        run: node generate_data.js

      - name: Check if chart_data.json was created
        run: |
          ls -l chart_data.json
          if [ ! -f chart_data.json ]; then
            echo "Error: chart_data.json was not created!"
            exit 1
          fi

      - name: Install AWS CLI (for R2 upload)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Upload data to Cloudflare R2
        run: |
          # GANTI 'data-chart-koin' dengan NAMA BUCKET R2 Anda
          aws s3 cp chart_data.json s3://${{ env.R2_BUCKET_NAME }}/chart_data.json \
            --endpoint-url ${{ env.AWS_ENDPOINT_URL }} \
            --region auto \
            --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          R2_BUCKET_NAME: data-chart-koin # <<--- GANTI DENGAN NAMA BUCKET R2 ANDA
