# .github/workflows/generate-chart-data.yml
name: Generate and Upload Multi-Coin Chart Data to R2

on:
  workflow_dispatch: # Memungkinkan Anda menjalankan workflow secara manual dari GitHub UI
  schedule:
    # Jalankan setiap 24 menit
    # CRON: menit jam hari_bulan bulan hari_minggu
    # Pastikan ini memberi cukup waktu untuk menyelesaikan proses pengambilan data (sekitar 3-5 menit untuk 250 koin)
    - cron: '*/24 * * * *' # Example: Runs at 0, 24, 48 minutes past the hour

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Menggunakan Node.js versi 20
          cache: 'npm' # Mengaktifkan caching untuk npm dependencies
          cache-dependency-path: package-lock.json # Path ke package-lock.json

      - name: Install dependencies
        run: npm ci # 'ci' (clean install) lebih baik untuk CI/CD dibanding 'install'

      - name: Generate Chart Data JSON
        run: node generate_data.js

      - name: Check if chart_data.json was created
        run: |
          ls -l chart_data.json
          if [ ! -f chart_data.json ]; then
            echo "Error: chart_data.json was not created!"
            exit 1
          fi

      - name: Install AWS CLI (for R2 upload)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version # Verifikasi instalasi

      - name: Upload data to Cloudflare R2
        run: |
          # GANTI 'data-chart-koin' dengan NAMA BUCKET R2 Anda
          aws s3 cp chart_data.json s3://${{ env.R2_BUCKET_NAME }}/chart_data.json \
            --endpoint-url ${{ env.AWS_ENDPOINT_URL }} \
            --region auto \
            --acl public-read # Penting agar file bisa diakses publik
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          R2_BUCKET_NAME: data-chart-koin # <<--- GANTI DENGAN NAMA BUCKET R2 ANDA
